#! /bin/bash

# update and install dependencies
sudo apt update
sudo apt install apt-transport-https ca-certificates curl software-properties-common gnupg lsb-release -y

# add docker repo and refresh
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update

# install docker
sudo apt install docker-ce -y
sudo usermod -aG docker $USER

# install docker compose
sudo curl -L https://github.com/docker/compose/releases/download/v2.26.1/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose

# start LibreChat app
git clone https://github.com/danny-avila/LibreChat.git
cd LibreChat/

# create required config file
cat > ./librechat.yaml <<EOF
# Configuration version (required)
version: 1.0.5
# This setting caches the config file for faster loading across app lifecycle
cache: true
EOF

# create env file
cp .env.example .env

# start app container
sudo docker-compose -f ./deploy-compose.yml up -d